### ISSUE TITLE
[Error] Failed to attach BPF program b'trace_func_entry' to kprobe

### ISSUE THREAD

**Issue by Naibaowjk** [UWNetworksLab/meshinsight#11]
Hello,
I use Ubuntu 20.04, and meshinsight commit is `f2e2142c5d5fe641ddc4a8675614c2d10e9eac5f`
```bash
Author: lbr <lichangxinlivingshade@gmail.com>
Date:   Sat Mar 25 21:56:20 2023 -0400

    set default CNI to flannel
```

wenn i run 
```bash
sudo python3 ./meshinsight/profiler/offline_profiler.py --latency --cpu -v
```

I received the error:
```
29-Mar-23 22:43:10 |    DEBUG | Running cmd: python3 /home/naibaoofficial/projects/meshinsight/meshinsight/profiler/latency/funclatency_filter.py -p 114620 ep_send_events_proc -d 30 -t 0
Traceback (most recent call last):
  File "/home/naibaoofficial/projects/meshinsight/meshinsight/profiler/latency/funclatency_filter.py", line 380, in <module>
    b.attach_kprobe(event_re=pattern, fn_name="trace_func_entry")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 835, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s"
Exception: Failed to attach BPF program b'trace_func_entry' to kprobe , it's not traceable (either non-existing, inlined, or marked as "notrace")
```

The python context is:
```python
# load BPF program
b = BPF(text=bpf_text)

# attach probes
if not library:
    b.attach_kprobe(event_re=pattern, fn_name="trace_func_entry")
    b.attach_kretprobe(event_re=pattern, fn_name="trace_func_return")
    matched = b.num_open_kprobes()
```

Could anyone help me to fix it? 
Thank you

**Comment by Romero027** [comment]
Thanks for trying MeshInsight! 

It's hard to tell what the issue is from the log you showed. Can you please provide more logs printed by the profiler? (e.g., from the very beginning.)

One thing to note is that I had issues with BCC installed via packages, so make sure you build it from the source.

**Comment by Naibaowjk** [comment]
> Thanks for trying MeshInsight!
> 
> It's hard to tell what the issue is from the log you showed. Can you please provide more logs printed by the profiler? (e.g., from the very beginning.)
> 
> One thing to note is that I had issues with BCC installed via packages, so make sure you build it from the source.

Thank you for you reply.
- I installed BCC via repos `./install.sh`, so i think that i build it from source.
- For more log(printed in sysout from the beginning):
![image](https://user-images.githubusercontent.com/17290838/228683537-73d34aae-9871-43ea-9f87-19c19af9cef1.png)

**Comment by Romero027** [comment]
Thanks! I suspect that the BPF program cannot find the `ep_send_events_proc`.

Maybe one thing you can do is omit the IPC component and analyze other components.

or you can try to use perf/flamegraph to see what is the call stack and replace the `ep_send_events_proc` with the correct IPC symbol.

**Comment by Naibaowjk** [comment]
> You should capture the Envoy process flamegraph, or it may be easier to capture the entire system flamegraph. You can refer to this website: https://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html.
> 
> Once you have the flamegraph, you can search for epoll and examine the call stack.

I check my kernel version, my version is `Linux 5.15.0-69-generic x86_64`
And this version don't have `ep_send_events_proc`, but with `ep_send_events` which do same work with `ep_send_events_proc`
```c
tatic int ep_send_events(struct eventpoll *ep,
			  struct epoll_event __user *events, int maxevents)
{
	struct epitem *epi, *tmp;
	LIST_HEAD(txlist);
	poll_table pt;
	int res = 0;

	/*
	 * Always short-circuit for fatal signals to allow threads to make a
	 * timely exit without the chance of finding more events available and
	 * fetching repeatedly.
	 */
	if (fatal_signal_pending(current))
		return -EINTR;

	init_poll_funcptr(&pt, NULL);

	mutex_lock(&ep->mtx);
	ep_start_scan(ep, &txlist);

	/*
	 * We can loop without lock because we are passed a task private list.
	 * Items cannot vanish during the loop we are holding ep->mtx.
	 */
	list_for_each_entry_safe(epi, tmp, &txlist, rdllink) {
		struct wakeup_source *ws;
		__poll_t revents;

		if (res >= maxevents)
			break;

		/*
		 * Activate ep->ws before deactivating epi->ws to prevent
		 * triggering auto-suspend here (in case we reactive epi->ws
		 * below).
		 *
		 * This could be rearranged to delay the deactivation of epi->ws
		 * instead, but then epi->ws would temporarily be out of sync
		 * with ep_is_linked().
		 */
		ws = ep_wakeup_source(epi);
		if (ws) {
			if (ws->active)
				__pm_stay_awake(ep->ws);
			__pm_relax(ws);
		}

		list_del_init(&epi->rdllink);

		/*
		 * If the event mask intersect the caller-requested one,
		 * deliver the event to userspace. Again, we are holding ep->mtx,
		 * so no operations coming from userspace can change the item.
		 */
		revents = ep_item_poll(epi, &pt, 1);
		if (!revents)
			continue;

		events = epoll_put_uevent(revents, epi->event.data, events);
		if (!events) {
			list_add(&epi->rdllink, &txlist);
			ep_pm_stay_awake(epi);
			if (!res)
				res = -EFAULT;
			break;
		}
		res++;
		if (epi->event.events & EPOLLONESHOT)
			epi->event.events &= EP_PRIVATE_BITS;
		else if (!(epi->event.events & EPOLLET)) {
			/*
			 * If this file has been added with Level
			 * Trigger mode, we need to insert back inside
			 * the ready list, so that the next call to
			 * epoll_wait() will check again the events
			 * availability. At this point, no one can insert
			 * into ep->rdllist besides us. The epoll_ctl()
			 * callers are locked out by
			 * ep_scan_ready_list() holding "mtx" and the
			 * poll callback will queue them in ep->ovflist.
			 */
			list_add_tail(&epi->rdllink, &ep->rdllist);
			ep_pm_stay_awake(epi);
		}
	}
	ep_done_scan(ep, &txlist);
	mutex_unlock(&ep->mtx);

	return res;
}
```

Then I changed the symbol from `ep_send_events_proc` to `ep_send_events` in `istio.yaml` .

BUT IT DOESN'T WORK :(

**Comment by Romero027** [comment]
Hmm, can you please share the error message you got?

**Comment by Romero027** [comment]
btw, it may be helpful if you ran the failed command separately
