### ISSUE TITLE
ValueError: Input y contains NaN

### ISSUE THREAD

**Issue by arjuntemura** [UWNetworksLab/meshinsight#13]
Hi 
I was getting the below error after running offline profiler for meshinsight: 

```
Traceback (most recent call last):
  File "./meshinsight/profiler/offline_profiler.py", line 604, in <module>
    latency_models = build_latency_model(latency_profile, request_sizes, p)
  File "./meshinsight/profiler/offline_profiler.py", line 271, in build_latency_model
    models['read_reg'] = linear_regression("read", read_data)
  File "./meshinsight/profiler/offline_profiler.py", line 262, in linear_regression
    reg = LinearRegression().fit(X, y)
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 648, in fit
    X, y = self._validate_data(
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1122, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1132, in _check_y
    y = check_array(
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 921, in check_array
    _assert_all_finite(
  File "/home/ryzen02/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input y contains NaN.
```

Before this error I was also getting some runtime warnings
```

/home/ryzen02/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ryzen02/.local/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/ryzen02/.local/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/ryzen02/.local/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/ryzen02/.local/lib/python3.8/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
```
I am running meshinsight on Ubuntu18.04 , kernel version 4.15 , python3.8 and istio 1.18.0.

**Comment by Romero027** [comment]
I suspect it has something to do with Istio/Envoy versions since we recently upgrade them.
